apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kasa.fullname" . }}
  labels:
    {{- include "kasa.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kasa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kasa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kasa.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          {{- range .Values.environment.envFrom }}
            - secretRef:
                name: {{ .secretName }}
            {{- end }} 
          env:
            {{- range .Values.environment.environmentSecrets }}
            - name: {{ .key }}
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- end }} 
            {{- range .Values.environment.environmentVariables }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }} 
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.endpoints.liveness }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelay }}
            periodSeconds: {{ .Values.probes.interval }}
            timeoutSeconds: {{ .Values.probes.timeout }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.endpoints.readiness }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelay }}
            periodSeconds: {{ .Values.probes.interval }}
            timeoutSeconds: {{ .Values.probes.timeout }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
