replicaCount: 1

image:
  repository: azureks.azurecr.io/kube-tools/nest-api
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: "nest"
fullnameOverride: "nest"

environment:
  envFrom:
    - secretName: kasa-env

probes:
  endpoints:
    liveness: "/api/health/alive"
    readiness: "/api/health/ready"
  initialDelay: 5
  interval: 10
  timeout: 120

serviceAccount:
  create: true
  name: "nest"

service:
  type: ClusterIP
  port: 80
  name: "nest"

ingress:
  enabled: false

resources:
  limits:
    cpu: 75m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 125Mi
    
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 90
